name: 05 - 2 Event Filters and Activity Types
on: 
    workflow_dispatch: 
        types: [closed]
        branches: main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: "echo Running whenever a PR is closed."
