name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: Whether to execute cache step
                default: true

jobs:
    build:
        defaults:
            run:
                working-directory: /13-caching/react-app.
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: '28.x'
            - name: Install dependencies
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"