name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: Whether to execute cache step
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x


jobs:
    install-deps:
        runs-on: ubuntu-latest
        outputs: 
            deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
        defaults:
            run:
                working-directory: 13-caching/react-app.
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{inputs.node-version}}
            - name: Calculate cache key
              id: cache-key
              run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" > "$GITHUB_OUTPUT"
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path: 13-caching/react-apps./node_modules
                key: ${{steps.cache-key.outputs.CACHE_KEY}}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
        
    lint-test:
        needs: install-deps
        defaults:
            run:
                working-directory: /13-caching/react-app.
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{inputs.node-version}}
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with: 
                path: 13-caching/react-app./node-modules
                key: ${{needs.install-deps.outputs.deps-cache-key}}
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Linting
              run: echo "Linting..."
    build:
        needs: install-deps
        defaults:
            run:
                working-directory: /13-caching/react-app.
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{inputs.node-version}}
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with: 
                path: 13-caching/react-app./node-modules
                key: ${{needs.install-deps.outputs.deps-cache-key}}
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"